"""Real PostgreSQL fault/recovery drill, isolated from the playable local database.

Run explicitly after the local host setup has created .cache/save-travel-config.json.
Only fresh, randomly named databases created by this test are ever removed.
"""
from __future__ import annotations

import copy
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import sys
import unittest
import uuid
from unittest.mock import patch

import psycopg
from psycopg import conninfo, sql

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "services/save_travel"))
from service import Service, digest

spec = importlib.util.spec_from_file_location("enfractal_recovery", ROOT / "tools/save-travel/recovery.py")
recovery = importlib.util.module_from_spec(spec)
spec.loader.exec_module(recovery)


class Client:
    def __init__(self, service, fixture):
        self.service, self.fixture, self.responses = service, fixture, {}

    def request(self, principal, op, **fields):
        result = self.responses.get(principal, {})
        request = {"op": op, "action_id": uuid.uuid4().hex}
        if op == "bootstrap":
            request.update(base_pin=self.fixture["empty"]["base_pin"], initial_home=self.fixture["populated"], empty_world=self.fixture["empty"])
        else:
            request.update(session_id=result.get("session_id"), world_id=result.get("world_id"), presence_epoch=result.get("presence_epoch"))
        request.update(fields)
        return request

    def submit(self, principal, request):
        result = self.service.dispatch(principal, request)
        if result.get("ok"):
            self.responses[principal] = result
        return result

    def call(self, principal, op, **fields):
        return self.submit(principal, self.request(principal, op, **fields))

    def prepare(self, principal, destination, **fields):
        result = self.responses[principal]
        return self.call(principal, "travel_prepare", destination_world_id=destination,
                         envelope=result["envelope"], expected_store_revision=result["store_revision"],
                         source_checkpoint=[-22.0, 0.0, 340.0], **fields)


class PostgresRecovery(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        config = json.loads((ROOT / ".cache/save-travel-config.json").read_text(encoding="utf-8-sig"))
        cls.admin_url = conninfo.make_conninfo(config["database_url"], dbname="postgres")
        cls.pg_bin = config["postgres_bin"]
        cls.godot = Path(os.getenv("ENFRACTAL_GODOT", str(ROOT / ".cache/godot/Godot_v4.7.2-stable_win64.exe")))
        result = cls.godot_fixture()
        cls.fixture = json.loads(next(line.split("|", 1)[1] for line in result.stdout.splitlines() if line.startswith("ENFRACTAL_CREATION_FIXTURE|")))
        cls.evidence = {"schema": "enfractal.recovery-drill", "version": 1,
                        "postgres": "17.6 local loopback", "scope": "same-machine isolated database restore", "checks": []}

    @classmethod
    def godot_fixture(cls, *args):
        result = subprocess.run([str(cls.godot), "--headless", "--path", str(ROOT / "game"),
                                 "--script", str(ROOT / "tests/save_travel_recovery/creation_fixture.gd"), "--", *args],
                                capture_output=True, text=True, timeout=30, check=False)
        if result.returncode:
            raise AssertionError("Godot creation fixture failed: " + result.stderr[-1200:])
        return result

    @classmethod
    def tearDownClass(cls):
        evidence_path = ROOT / ".cache/recovery/latest-drill.json"
        evidence_path.parent.mkdir(parents=True, exist_ok=True)
        evidence_path.write_text(json.dumps(cls.evidence, indent=2) + "\n", encoding="utf-8")

    def setUp(self):
        self.suffix = uuid.uuid4().hex[:16]
        self.source_name = "enfractal_recovery_" + self.suffix
        self.created = []
        with psycopg.connect(self.admin_url, autocommit=True) as admin:
            admin.execute(sql.SQL("CREATE DATABASE {} TEMPLATE template0").format(sql.Identifier(self.source_name)))
        self.created.append(self.source_name)
        self.addCleanup(self.drop_owned_databases)
        self.source_url = conninfo.make_conninfo(self.admin_url, dbname=self.source_name)
        self.service = Service(self.source_url)
        self.client = Client(self.service, self.fixture)
        self.ok(self.client.call("local_player", "bootstrap"))
        self.ok(self.client.call("guest_player", "bootstrap"))

    def drop_owned_databases(self):
        with psycopg.connect(self.admin_url, autocommit=True) as admin:
            for name in self.created:
                if name not in ("enfractal_recovery_" + self.suffix, "enfractal_restore_" + self.suffix):
                    raise AssertionError("Refusing to remove a database not generated by this test.")
                admin.execute(sql.SQL("DROP DATABASE {} WITH (FORCE)").format(sql.Identifier(name)))

    def ok(self, result):
        self.assertTrue(result.get("ok"), result)
        return result

    def state(self, database_url=None):
        with psycopg.connect(database_url or self.source_url) as connection:
            return recovery.database_snapshot(connection)

    def create_sandbox(self, principal="local_player"):
        return self.ok(self.client.call(principal, "create_sandbox", name="Recovery drill", gravity=0.25))["sandbox_id"]

    def cross(self, principal, destination, stop="arrived", **fields):
        prepared = self.ok(self.client.prepare(principal, destination, **fields))
        transfer = prepared["transfer_id"]
        if stop == "prepared":
            return transfer
        self.ok(self.client.call(principal, "travel_freeze", transfer_id=transfer))
        if stop == "frozen":
            return transfer
        self.ok(self.client.call(principal, "travel_commit", transfer_id=transfer, expected_rules_revision=prepared["destination_rules"]["revision"]))
        if stop == "committed":
            return transfer
        self.ok(self.client.call(principal, "travel_arrive", transfer_id=transfer))
        return transfer

    def test_01_actual_backup_restore_preserves_editable_sources_receipts_and_presence(self):
        destination = self.create_sandbox()
        invitation = self.ok(self.client.call("local_player", "invite", sandbox_id=destination, recipient="guest_player", role="editor"))["invite_id"]
        transfer = self.cross("guest_player", destination, stop="committed", invite_id=invitation)
        before = self.state()
        bundle = ROOT / ".cache/recovery" / ("drill_" + self.suffix)
        backup = recovery.backup(self.source_url, self.pg_bin, bundle, ROOT, self.godot)
        manifest = recovery.verify(bundle)
        restored_name = "enfractal_restore_" + self.suffix
        restored = recovery.restore(self.admin_url, self.pg_bin, bundle, restored_name)
        self.created.append(restored_name)
        restored_url = conninfo.make_conninfo(self.admin_url, dbname=restored_name)
        after = self.state(restored_url)
        self.assertEqual(before, after)
        self.assertEqual(digest(before), manifest["database_snapshot_sha256"])
        self.assertEqual(before["receipts"], after["receipts"])
        self.assertEqual(len(after["worlds"]["home"]["envelope"]["instances"]), 1)
        self.assertEqual(after["worlds"][destination]["envelope"]["instances"], [])
        self.assertEqual(after["invites"][invitation]["remaining_uses"], 0)
        self.assertEqual(after["presence"]["guest_player"]["world_id"], destination)
        self.assertEqual(after["transfers"][transfer]["state"], "committed")
        envelope_path = bundle / "restored-envelope-check.json"
        envelope_path.write_text(json.dumps(after["worlds"]["home"]["envelope"]), encoding="utf-8")
        checked = self.godot_fixture("--verify-envelope", str(envelope_path))
        self.assertIn('"ok":true', checked.stdout)
        resumed = Client(Service(restored_url), self.fixture)
        stale = resumed.service.dispatch("guest_player", self.client.request("guest_player", "status"))
        self.assertFalse(stale["ok"])
        fresh = self.ok(resumed.call("guest_player", "bootstrap"))
        self.assertEqual(fresh["world_id"], destination)
        self.assertEqual(len(self.state(restored_url)["presence"]), 2)
        self.assertEqual(self.state(restored_url)["invites"][invitation]["remaining_uses"], 0)
        pending = fresh["status"]["pending"]
        if pending:
            self.ok(resumed.call("guest_player", "travel_arrive", transfer_id=pending["id"]))
        with self.assertRaisesRegex(recovery.RecoveryError, "already exists"):
            recovery.restore(self.admin_url, self.pg_bin, bundle, restored_name)
        self.assertEqual(before, self.state())
        self.evidence["checks"].append({"name": "real backup / isolated restore", "passed": True,
                                        "backup_seconds": backup["backup_seconds"], "restore_seconds": restored["restore_seconds"],
                                        "source_instances": 1, "worlds": len(after["worlds"]), "receipts": len(after["receipts"]),
                                        "control_receipts": len(after.get("control_receipts", {})),
                                        "source_files": len(manifest["files"]), "snapshot_sha256": digest(before), "bundle": str(bundle)})

    def test_02_unknown_commit_retry_is_one_durable_effect(self):
        request = self.client.request("local_player", "create_sandbox", name="One world", gravity=0.25)
        first = self.ok(self.client.submit("local_player", request))
        second = self.ok(self.client.submit("local_player", copy.deepcopy(request)))
        self.assertTrue(second["replayed"])
        self.assertEqual(first["sandbox_id"], second["sandbox_id"])
        self.assertEqual(len(self.state()["worlds"]), 2)
        changed = {**request, "name": "Changed payload"}
        self.assertEqual(self.client.submit("local_player", changed)["code"], "action_id_conflict")

    def test_03_new_host_fences_both_old_sessions(self):
        newer = Service(self.source_url)
        for principal in ("local_player", "guest_player"):
            request = self.client.request(principal, "create_sandbox", name="Stale host", gravity=0.25)
            result = self.service.dispatch(principal, request)
            self.assertFalse(result["ok"])
            self.assertEqual(result["code"], "host_stale")
        self.ok(Client(newer, self.fixture).call("local_player", "bootstrap"))
        self.assertEqual(len(self.state()["worlds"]), 1)

    def test_04_revoked_invitation_cannot_commit_prepared_crossing(self):
        destination = self.create_sandbox()
        invite = self.ok(self.client.call("local_player", "invite", sandbox_id=destination, recipient="guest_player"))["invite_id"]
        transfer = self.cross("guest_player", destination, stop="frozen", invite_id=invite)
        self.ok(self.client.call("local_player", "revoke", invite_id=invite))
        denied = self.client.call("guest_player", "travel_commit", transfer_id=transfer, expected_rules_revision=1)
        self.assertFalse(denied["ok"])
        self.assertEqual(self.state()["presence"]["guest_player"]["world_id"], "home")
        self.assertEqual(self.state()["invites"][invite]["remaining_uses"], 1)

    def test_05_changed_rules_cannot_commit_prepared_crossing(self):
        destination = self.create_sandbox()
        transfer = self.cross("local_player", destination, stop="frozen")
        self.ok(self.client.call("local_player", "set_rules", sandbox_id=destination, expected_rules_revision=1, gravity=1.0))
        denied = self.client.call("local_player", "travel_commit", transfer_id=transfer, expected_rules_revision=1)
        self.assertEqual(denied["code"], "rules_changed")
        self.assertEqual(self.state()["presence"]["local_player"]["world_id"], "home")

    def test_06_source_slot_remains_until_arrival_ack(self):
        first = self.create_sandbox()
        second = self.create_sandbox("guest_player")
        self.cross("local_player", first)
        transfer = self.cross("local_player", "home", stop="committed")
        blocked = self.client.prepare("guest_player", second)
        self.assertEqual(blocked["code"], "sandbox_slot_busy")
        self.ok(self.client.call("local_player", "travel_arrive", transfer_id=transfer))
        self.ok(self.client.call("guest_player", "world_load"))
        self.ok(self.client.prepare("guest_player", second))

    def test_07_restarts_at_each_transfer_checkpoint_keep_one_presence(self):
        destination = self.create_sandbox()
        for stage in ("prepared", "frozen", "committed", "arrived"):
            with self.subTest(stage=stage):
                crashed = subprocess.run([sys.executable, str(ROOT / "tests/save_travel_recovery/crash_worker.py")],
                                         input=json.dumps({"database_url": self.source_url, "fixture": self.fixture,
                                                           "destination": destination, "stage": stage}),
                                         text=True, capture_output=True, timeout=20, check=False)
                self.assertEqual(crashed.returncode, 73, crashed.stderr)
                matching = [transfer for transfer in self.state()["transfers"].values()
                            if transfer["destination"] == destination]
                transfer = max(matching, key=lambda item: item["prepared_at"])["id"]
                self.service = Service(self.source_url)
                self.client = Client(self.service, self.fixture)
                resumed = self.ok(self.client.call("local_player", "bootstrap"))
                expected = destination if stage in ("committed", "arrived") else "home"
                self.assertEqual(resumed["world_id"], expected)
                current = self.state()
                self.assertEqual(len([p for p in current["presence"] if p == "local_player"]), 1)
                self.assertIn(current["transfers"][transfer]["state"], ("cancelled", "committed", "arrived"))
                if resumed["status"]["pending"]:
                    self.ok(self.client.call("local_player", "travel_arrive", transfer_id=transfer))
                if expected != "home":
                    returned = self.ok(self.client.call("local_player", "return_home"))
                    if returned["status"]["pending"]:
                        self.ok(self.client.call("local_player", "travel_arrive", transfer_id=returned["status"]["pending"]["id"]))

    def test_08_dump_and_manifest_share_snapshot_during_concurrent_commit(self):
        original_tool = recovery.pg_tool
        inserted = []

        def insert_after_export(bin_dir, name, args, env, timeout=120):
            if name == "pg_dump" and "--format=custom" in args:
                inserted.append(self.create_sandbox())
            return original_tool(bin_dir, name, args, env, timeout)

        bundle = ROOT / ".cache/recovery" / ("concurrent_" + self.suffix)
        with patch.object(recovery, "pg_tool", insert_after_export):
            recovery.backup(self.source_url, self.pg_bin, bundle, ROOT, self.godot)
        self.assertEqual(len(inserted), 1)
        self.assertEqual(len(self.state()["worlds"]), 2)
        restored_name = "enfractal_restore_" + self.suffix
        recovery.restore(self.admin_url, self.pg_bin, bundle, restored_name)
        self.created.append(restored_name)
        restored = self.state(conninfo.make_conninfo(self.admin_url, dbname=restored_name))
        self.assertEqual(len(restored["worlds"]), 1)
        self.assertNotIn(inserted[0], restored["worlds"])

    def test_09_unknown_commit_lookup_survives_restart_without_cross_account_leak(self):
        request = self.client.request("local_player", "create_sandbox", name="Lost response", gravity=0.25)
        committed = self.ok(self.client.submit("local_player", request))
        self.client = Client(Service(self.source_url), self.fixture)
        self.ok(self.client.call("local_player", "bootstrap"))
        self.ok(self.client.call("guest_player", "bootstrap"))
        looked_up = self.ok(self.client.call("local_player", "action_lookup", action_id_to_lookup=request["action_id"]))
        self.assertTrue(looked_up["action_found"])
        self.assertEqual(looked_up["action_receipt"]["sandbox_id"], committed["sandbox_id"])
        hidden = self.ok(self.client.call("guest_player", "action_lookup", action_id_to_lookup=request["action_id"]))
        self.assertFalse(hidden["action_found"])
        self.assertEqual(hidden["action_receipt"], {})
        self.assertEqual(len(self.state()["worlds"]), 2)


if __name__ == "__main__":
    unittest.main(verbosity=2)
